bibliotecaLocal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView

urlpatterns = [
	path('', RedirectView.as_view(url='/catalogo/', permanent=True)),
	path('catalogo/', include('catalogo.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Adicionar urls de autenticação de site Django (para login, logout, gerenciamento de senha)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
# from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
# from django.conf import settings
# from django.conf.urls.static import static

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalogo/urls.py
# Use include() to add paths from the catalog application
from django.conf.urls import include
from django.urls import path

from catalogo import views

urlpatterns = [
    # path('catalogo/', include('catalogo.urls')),
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.book_detail_view, name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.author_detail_view, name='author-detail'),
    # path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
]

urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

urlpatterns += [
    path('b-mybooks/', views.BibliotecaBooksByUserListView.as_view(), name='b-books'),
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookrDelete.as_view(), name='book-delete'),
]

catalogo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date



import uuid # Obrigatório para instâncias de livro exclusivas

# Create your models here.
class Genero(models.Model):
    """
    Modelo que representa um gênero de livro.
    """

    name = models.CharField(max_length=200, help_text='Insira o gênero de um livro (por exemplo, ficção científica)')

    def __str__(self):
        """String para representar o Modelo de objeto."""
        return self.name

class Livro(models.Model):
    """
    Modelo que representa um livro (mas não uma cópia específica de um livro).
    """
    titulo = models.CharField(max_length=200)
    # Chave estrangeira usada porque o livro pode ter apenas um autor, mas os autores podem ter vários livros
    # Autor como uma string em vez de um objeto porque ainda não foi declarado no arquivo
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    #summary
    resumo = models.TextField(max_length=1000, help_text='Insira uma breve descrição do livro')
    isbn = models.CharField(
        'ISBN', max_length=13,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
        )
    # ManyToManyField usado porque o gênero pode conter muitos livros. Os livros podem abranger muitos gêneros.
    # A classe de gênero já foi definida para que possamos especificar o objeto acima.
    genero = models.ManyToManyField(
        Genero, help_text='Selecione um gênero para este livro'
        )

    def __str__(self):
        """String for representing the Model object."""
        return self.titulo
    def get_absolute_url(self):
        """Retorna o url para acessar um registro de detalhes deste livro."""
        return reverse('book-detail', args=[str(self.id)])
    def display_genero(self):
        """
        Crie uma string para o Gênero. Isso é necessário para exibir o gênero no Admin.
        """
        return ', '.join(genero.name for genero in self.genero.all()[:3])

    display_genero.short_description = 'Genero'



class InstanciaLivro(models.Model):
    """
    Modelo que representa uma cópia específica de um livro (ou seja, que pode ser emprestado da biblioteca).
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='ID exclusivo para este livro específico em toda a biblioteca'
        )
    livro = models.ForeignKey('Livro', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    STATUS_EMPRESTIMO = (
        ('M', 'Manutenção'),
        ('E', 'Por empréstimo'),
        ('A', 'Acessível'),
        ('R', 'Reservado'),
    )
    status = models.CharField(
        max_length=1,
        choices=STATUS_EMPRESTIMO,
        blank=True,
        default='m',
        help_text='Disponibilidade de livros',
    )

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
    
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.livro.titulo})'
    @property
    def is_overdue(self):
        # se uma determinada instância do livro está atrasada. 
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Autor(models.Model):
    """
    Modelo que representa um autor.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalogo/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


# form de renovacao de livros
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Insira uma data entre agora e 4 semanas (padrão 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        # Verifique se a data não está no passado.
        if data < datetime.date.today():
            raise ValidationError(_('Data inválida - renovação no passado'))
        # Verifique se uma data está no intervalo permitido (+4 semanas a partir de hoje).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Data inválida - renovação com mais de 4 semanas de antecedência '))

        # Remember to always return the cleaned data.
        return data


from catalogo.models import Livro


class BookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields.keys():
            self.fields[f].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Livro
        fields = [
            'titulo',
            'autor',
            'resumo',
            'isbn',
            'genero'
        ]


from catalogo.models import Autor

class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
        initial = {'date_of_death': '11/06/2020'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields.keys():
            # adicionada classes css em cada campo do form
            self.fields[f].widget.attrs.update({'class': 'form-control'})

catalogo/views.py
from django.shortcuts import render
from catalogo.models import Livro, Autor, InstanciaLivro, Genero


# Create your views here.
def index(request):
    """View function for home page of site."""

    # Gerar contagens de alguns dos objetos principais
    num_books = Livro.objects.all().count()
    num_instances = InstanciaLivro.objects.all().count()
    # Livros disponíveis (status = 'a')
    num_instances_available = InstanciaLivro.objects.filter(status__exact='A').count()
    # O 'all ()' é implícito por padrão.
    num_authors = Autor.objects.count()
    num_genres = Genero.objects.all().count()

    # Número de visitas a esta view, conforme contado na variável de sessão.
    num_visits = request.session.get('num_visits', 1) # busca 'num_visits' se vazio retorna 1
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_visits': num_visits,

    }
    # Renderize o template HTML index.html com os dados na variável de contexto
    return render(request, 'index.html', context=context)

from django.views import generic

class BookListView(generic.ListView):
    model = Livro
    # context_object_name  = 'my_book_list' # seu próprio nome para a lista como uma variável de modelo
    # queryset = Livro.objects.filter(titulo__icontains='Mil')[:5] # Obtenha 5 livros contendo 'guerra' no título
    # Especifique seu próprio nome / local de modelo
    template_name = 'catalog/book_list.html'
    paginate_by = 2


    def get_context_data(self, **kwargs):
        # Chame a implementação de base primeiro para obter o contexto
        context = super(BookListView, self).get_context_data(**kwargs)
        # Crie quaisquer dados e adicione-os ao contexto
        context['some_data'] = 'Estes são apenas alguns dados'
        return context
    def get_queryset(self):
        return Livro.objects.all()
        # return Livro.objects.filter(titulo__icontains='Mil')[:2]

from django.shortcuts import get_object_or_404

class BookDetailView(generic.DetailView):
    model = Livro
    template_name = 'catalog/book_detail.html'
    # context_object_name  = 'author'
    

    
    # queryset = Livro.objects.all()

    # def get_queryset(self, *args, **kwargs):
    #     return Livro.objects.filter(pk=self.kwargs['pk'])
    # def get_queryset(self):
    #     obj = super().get_object()
    #     obj = Livro.objects.get(pk=self.kwargs["pk"])

        # return obj
    # def get_object(self):
    #     return Livro.objects.get(pk=self.kwargs['pk'])
    # def get(self, request, pk):
    #     self.context = Livro.objects.get(pk=pk)
        
        
        
    # def get_object(self, pk):
    #     obj = super().get_object()
    #     # Record the last accessed date
    #     return obj

def book_detail_view(request, pk):
    book = get_object_or_404(Livro, pk=pk)
    return render(request, 'catalog/book_detail.html', context={'book': book})

# view baseadas em classe
class AuthorListView(generic.ListView): # 1 uma classe para view in lista
    model = Autor                       # na page a variavel e autor
    template_name = 'catalog/author_list.html'
    paginate_by = 2
    def get_context_data(self, **kwargs):
        # Chame a implementação de base primeiro para obter o contexto
        context = super(AuthorListView, self).get_context_data(**kwargs)
        return context
    def get_queryset(self):
        return Autor.objects.all()

class AuthorDetailView(generic.DetailView): # 2 classe para detalhes
    model = Autor   
    template_name = 'catalog/author_detail.html'

def author_detail_view(request, pk):
    author = get_object_or_404(Autor, pk=pk)
    books =Livro.objects.filter(autor__pk=pk)

    return render(request, 'catalog/author_detail.html', context={'author': author, 'books':books})


from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    'Generic class-based view' que lista livros emprestados ao usuário atual.
    """
    model = InstanciaLivro
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return InstanciaLivro.objects.filter(borrower=self.request.user).filter(status__exact='E').order_by('due_back')


from django.contrib.auth.mixins import PermissionRequiredMixin

class BibliotecaBooksByUserListView(PermissionRequiredMixin, generic.ListView):
    """
    'Generic class-based view' que lista livros emprestados ao usuário atual.
    """
    model = InstanciaLivro
    template_name = 'catalog/book_list_biblioteca.html'
    # Or multiple permissions
    permission_required = 'catalogo.can_mark_returned'
    paginate_by = 2

    def get_queryset(self):
        return InstanciaLivro.objects.filter(status__exact='E').order_by('due_back')


import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalogo.forms import RenewBookForm

@login_required
@permission_required('catalogo.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """
    Função de visualização para renovar um BookInstance específico pelo bibliotecário.
    """
    book_instance = get_object_or_404(InstanciaLivro, pk=pk)
    # Se esta for uma solicitação POST, processe os dados do formulário
    if request.method == 'POST':
        # Crie uma instância de formulário e preencha-a com os dados da solicitação (binding):
        form = RenewBookForm(request.POST)
        # Verifique se o formulário é válido:
        if form.is_valid():
            # processe os dados em form.cleaned_data conforme necessário (aqui, apenas os gravamos no campo due_back do modelo)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            # redirect to a new URL name:
            return redirect('b-books')
    # Se este for um GET (ou qualquer outro método), crie o formulário padrão.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)




from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from catalogo.models import Autor
from catalogo.forms import AutorForm

class AuthorCreate(CreateView):
    model = Autor
    # fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    form_class = AutorForm
    initial = {'date_of_death': '11/06/2020'}
    template_name = 'catalog/author_form.html'
    
class AuthorUpdate(UpdateView):
    model = Autor
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'
class AuthorDelete(DeleteView):
    model = Autor
    success_url = reverse_lazy('authors')



from django.views.generic.edit import CreateView
from catalogo.forms import BookForm

class BookCreate(CreateView):
    template_name = 'catalog/book_form.html'
    model = Livro
    form_class = BookForm
    # fieldsets = (

    # )
    # fields = ('titulo', 'autor', 'resumo','isbn', 'genero')

     # self.fields['titulo'].widget.attrs.update({'class': 'form-control'})


    # fields = ['titulo', 'autor', 'resumo', 'isbn', 'genero']


from django.views.generic.edit import UpdateView, DeleteView
from catalogo.forms import BookForm
from django.urls import reverse_lazy

class BookUpdate(UpdateView):
    template_name = 'catalog/book_form.html'
    model = Livro
    form_class = BookForm

class BookrDelete(DeleteView):
    template_name = 'catalog/book_confirm_delete.html'
    model = Livro
    # reverse_lazy retorna para a url name
    success_url = reverse_lazy('books')

catalogo/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Delete Author</h1>

    <p>Are you sure you want to delete the author: {{ author }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>

{% endblock %}

catalogo/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container mt-5">
        <h1>Author: {{ author.last_name }}, {{ author.first_name }}</h1>
        <p class="text-muted">{{ author.date_of_birth }}</p>
    </div>
    
    <div class="container mt-4">
        <div class="row">
            <h2 class="h3">Books:</h2>
        </div>
        {% if books %}
            {% for book in books %}
                <div class="row d-block">
                    <a href="http://">{{ book.titulo }}</a>
                    
                    
                    <p class="lead">{{ book.resumo }}</p>
                    
                    <hr class="w-100">
                </div>
                
                
            {% endfor %}
        {% else %}
            <p class="warning">
                sem livros.
            </p>
        {% endif %}
    </div>
    <!-- <p><strong>Language:</strong> {{ book.language }}</p> -->
    

    
{% endblock %}

catalogo/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Submit</button>
        
    </form>
{% endblock %}

catalogo/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if autor_list %}
        <ul>
            {% for autor in autor_list %}
                <li>
                    <a href="{% url 'author-detail' autor.id %}">{{ autor.first_name }} {{ autor.last_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no Authors in the library.</p>
    {% endif %} 
    
{% endblock %}

catalogo/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Delete Book</h1>

    <p>Are you sure you want to delete the book: {{ livro.titulo }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit" value="">Yes, delete."</button>
    </form>

{% endblock %}

catalogo/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.titulo }}</h1>

    <p><strong>Autor:</strong> <a href="">{{ book.autor }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.resumo }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <!-- <p><strong>Language:</strong> {{ book.language }}</p> -->
    <p><strong>Genre:</strong> {{ book.genero.all|join:", " }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.instancialivro_set.all %}
        <hr>
        <p class="{% if copy.status == 'A' %}text-success{% elif copy.status == 'M' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
            <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

catalogo/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_titulo">{{form.titulo.label}}:</label>
            <!-- <input type="email" class="form-control" placeholder="" id=""> -->
            {{ form.titulo }}
        </div>
        <div class="form-group">
            <label for="id_autor">Autor:</label>
            {{ form.autor }}
            <!-- <input type="password" class="form-control" placeholder="Enter password" id="pwd"> -->
        </div>
        <div class="form-group">
            <label for="id_resumo">Resumo:</label>
            {{ form.resumo }}
            <!-- <input type="password" class="form-control" placeholder="Enter password" id="pwd"> -->
        </div>
        <div class="form-group">
            <label for="id_isbn">ISBN:</label>
            {{ form.isbn }}
            <!-- <input type="password" class="form-control" placeholder="Enter password" id="pwd"> -->
        </div>
        <div class="form-group">
            <label for="id_genero">Genero:</label>
            {{ form.genero }}
            <!-- <input type="password" class="form-control" placeholder="Enter password" id="pwd"> -->
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

catalogo/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if livro_list %}
        
            
            {% for book in livro_list %}
                <div class="row align-items-center my-5">
                    <div class="col-sm-8 text-wraper">
                        <ul>
                            <li class="">
                                <a href="{{ book.get_absolute_url }}" class="mx-2">{{ book.titulo }}</a> ({{book.autor}})
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-4 d-flex justify-content-center">
                        {% if perms.catalogo.can_mark_returned %}
                            <a class="btn btn-sm btn-primary mx-2" href="{% url 'book-update' book.pk %}">
                                Update
                            </a>
                            <a href="{% url 'book-delete' book.pk %}" class="btn btn-warning mx-2">
                                Delete
                            </a>  
                        {% endif %}
                    </div>
                </div>
                <hr>

            {% endfor %}
            
        
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %} 
    <!-- {{livro_list.some_data}} -->
{% endblock %}

catalogo/templates/catalog/book_list_biblioteca.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed books</h1>

    {% if instancialivro_list %}

    <table class="table table-dark">
        <thead>
            <tr>
                <th class="text-center">
                    Titulo:
                </th>
                <th>
                    Pertencente:
                </th>
            </tr>
        </thead>
        <tbody>
            {% for bookinst in instancialivro_list %}
            <tr>
                {% if bookinst.livro.titulo %}
                    <td class="text-center">
                        
                        <a href="/catalogo/book/{{bookinst.livro.id}}">
                            {{bookinst.livro.titulo}}
                        </a>
                    </td>
                    <td class="lead">
                        ({{ bookinst.borrower.get_username|upper }})
                    </td>
                    <td>
                        {% if perms.catalogo.can_mark_returned %}- 
                            <a href="{% url 'renew-book-librarian' bookinst.id %}">
                                Renew
                            </a>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
            {% endfor %}

        </tbody>
    </table>

    {% else %}
      <p class="display-2">Não há livros emprestados.</p>
    {% endif %}
{% endblock %}

catalogo/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalogo/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if instancialivro_list %}
    <ul>

      {% for bookinst in instancialivro_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.livro.pk %}">{{bookinst.livro.titulo}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Não há livros emprestados.</p>
    {% endif %}
{% endblock %}